# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-06 18:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_action',
            name='pdu',
        ),
    ]
