# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_user_action_pdu'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlet',
            name='number',
            field=models.IntegerField(default=1),
        ),
    ]
