# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-10 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_outlet_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='outlets',
            field=models.ManyToManyField(to='main.Outlet'),
        ),
    ]
